[package]
name = "auth-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.71"
ed25519-dalek = { version = "2.1.1", features = ["signature"]}
hex = "0.4.3"
prost = "^0.13"
prost-build = "^0.13"
thiserror = "^2.0"

[build-dependencies]
prost = "^0.13"
prost-build = "^0.13"
