[package]
name = "certifier"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
auth-rs = { path = "../auth-rs" }
clap = { version = "4.5.27", features = ["derive"] }
ed25519-dalek = "2.1.1"
hex = "0.4.3"
